config/routes.rb
Pigeonhole::Application.routes.draw do |map|
  
  # Logout should, of course, work without language
  get 'logout' => 'pigeonhole#logout', :as => 'logout'
  
  constraints(:locale => /[a-z]{2}/) do
    scope "(:locale)" do
      
      get 'logout' => 'pigeonhole#logout', :as => 'logout'
      
      # Self-destructive Binary
      resources :binaries, :only => [:new, :create] do
        member do
          post :new # binaries/new has a password login, we want it to accept POST requests.
        end
      end
      get ':id/:key' => 'binaries#show', :as => 'show_binary', :constraints => { :id => /[a-z0-9]{8}/, :key => /[a-zA-Z0-9]{20}/ }
      
      # Self-destructive Tape
      resources :tapes, :only => [:new, :create] do
        member do
          post :new # tapes/new has a password login, we want it to accept POST requests.
          post :download
        end
      end
      get ':id/:key' => 'tapes#show', :as => 'show_tape', :constraints => { :id => /[a-z0-9]{6}/, :key => /[a-zA-Z0-9]{20}/ }
      
      # Message in a safe
      resources :messages, :only => [:new, :create, :destroy] do
        member do
          post :new # messages/new has a password login, we want it to accept POST requests.
          post :download
          post :attachment
        end
      end
      match ':id' => 'messages#show', :as => 'show_message', :constraints => { :id => /[a-z0-9]{6}/ }
      
      root :to => "pigeonhole#index"
      
    end
  end
end

app/models/message.rb
class Message < Package

  attr_accessor :attachment, :mime, :name
  
  def initialize(args={})
    super
    @id         = args.fetch(:id, SecureRandom.hex(3))
    @attachment = args.fetch(:attachment, nil)
    @mime       = args.fetch(:mime, 'text/plain')
    @name       = args.fetch(:name, filename)
    self
  end

  validates :key, :presence => true, :length => { :within => 9..20 }
  
  def serialize
    { :body => body,
      :attachment => attachment,
      :time => time,
      :mime => mime,
      :name => name }.to_yaml
  end
  
  def unserialize(raw)
    yaml = YAML.load(raw)
    @body       = yaml.fetch(:body, nil)
    @attachment = yaml.fetch(:attachment, nil)
    @time       = yaml.fetch(:time, nil)
    @mime       = yaml.fetch(:mime, nil)
    @name       = yaml.fetch(:name, nil)
    self
  end
  
  def to_download
    timestamp + ", Attachment: #{name}" + "\n" + Array.new((20 + (name.length/2)), '.').join(' ') + "\n\n" + body
  end
  

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  before_filter :login_required, :except => [ :show ]
  after_filter :lock_open_messages, :except => [ :show, :download, :attachment ]
  
  # GET/POST
  def show
    # The show method reacts only to GET requests by convention
    # We want it to accept a password via POST, store the password in the session and then redirect it to the GET request
    redirect_to show_message_url, :flash => { :password => params[:password] } and return if request.post?
    # There is a little work-around here, because we cannot save anything in the session here except via the flash
    session[:password] = flash[:password] if flash[:password].present?
    @message = Message.find(:id => params[:id], :key => session[:password])
    render :template => 'messages/password' and return unless @message
    perform_login # On successful read, log in the user
  end
  
  # POST
  def download
    @message = Message.find(:id => params[:id], :key => session[:password])
    send_data @message.to_download, :filename => @message.filename, :type => 'text/plain' and return
  end
  
  # POST
  def attachment
    @message = Message.find(:id => params[:id], :key => session[:password])
    send_data @message.attachment, :filename => @message.name, :type => @message.mime and return
  end
  
  def new
    @message = Message.new
  end
  
  def create
    @message = Message.new(:body => params[:body], :key => params[:password])
    @message.errors.add(:key, t('errors.messages.confirmation')) if params[:password] != params[:password_confirmation]
    if params[:upload].present?
      @message.name       = params[:upload].original_filename
      @message.mime       = params[:upload].content_type
      @message.attachment = params[:upload].read
    end
    if @message.save
      @pickup_url = show_message_url(@message.id, :locale => nil)
      # Prevent double sending the form
      session[:_csrf_token] = ActiveSupport::SecureRandom.base64(32)
    else
      render :template => 'messages/new' and return
    end
  end
  
  def destroy
    @message = Message.find(:id => params[:id], :key => session[:password])
    @message.try(:destroy)
    redirect_to root_url and return
  end
  
end

app/views/messages/create.html.erb
<div id="header">
  <%= link_to random_tape_image, root_url  %><br/>
  <%=t '.headline' %>
</div>

<div id="tape" class="pickup">
  <%= @pickup_url %>
</div>

<%= info_block %>

<div id="footer">
  <%= menu_link %>
</div>

app/views/messages/new.html.erb
<div id="header">
  <% if @message.errors.empty?  %>
    <%=t '.headline' %><br/>
  <% else %>
    <strong><%= @message.errors.full_messages.join('<br/>').html_safe %></strong>
  <% end %>
</div>

<%= form_tag messages_url, { :multipart => true } do -%>

  <div id="tape">
    <%= text_area_tag :body, @message.body %><br/><br/>
    <div id="attachment">
      <%=t '.attachment' %><br/>
      <%= file_field_tag :upload %><br/>
    </div>
    <div id="password">
      <%=t '.password' %><br/>
      <%= password_field_tag :password %>
      <%= password_field_tag :password_confirmation %>
    </div>
    <div class="clear"></div>
  </div>

  <div id="footer">
    <div class="menu_two_items">
      <div class="menu_item">
        <%= image_submit_tag("message.png", :height => 61) %><br/>
        <%=t '.submit' %>
      </div>
      <div class="menu_item">
        <%= link_to image_tag('trash.png', :height => 61), root_url %><br/>
        <%=t 'cancel' %>
      </div>
    </div>
  </div>
  <div class="clear"></div>

<% end %>


<%= info_block %>

<%= focus_on :body %>

app/views/messages/password.html.erb
<br/><br/><br/><br/><br/><br/>

<div id="header">
  <%= image_tag 'message.png', :height => 61 %><br/>
  <%= form_tag show_message_url do %>
    <div><%= password_field_tag 'password' %></div>
  <% end %>
</div>

<%= focus_on :password %>

app/views/messages/show.html.erb
<div id="header">
  <%= link_to random_tape_image, root_url  %><br/>
  <%=t '.headline' %>
</div>

<div id="tape">
  <%=raw sanitize(h(@message.body).with_line_breaks) %>
  <br/>
  <div class="metadata"><%= @message.timestamp %></div>
</div>

<div id="footer">
  <% unless @message.attachment %>
  <div class="menu_three_items">
  <% end %>
    <div class="menu_item">
      <% form_tag download_message_url, :remote => true do |form| %>
        <%= image_submit_tag("download.png", :height => 61) %><br/>
      <% end %>
      <%=t '.download' %>
    </div>
    <% if @message.attachment %>
      <div class="menu_item">
        <% form_tag attachment_message_url, :remote => true do |form| %>
          <%= image_submit_tag("download.png", :height => 61) %><br/>
        <% end %>
        <%= @message.name %>
      </div>
    <% end %>
    <div class="menu_item">
      <% form_tag url_for(:action => :destroy, :id => @message.id), :method => :delete do |form| %>
        <%= image_submit_tag("trash.png", :height => 61) %><br/>
        <%=t '.delete' %>
      <% end %>
    </div>
    <div class="menu_item">
      <%= link_to image_tag('message.png', :height => 61), root_url %><br/>
      <%=raw t('.reply') %>
    </div>
  <% unless @message.attachment %>
  </div>
  <% end %>
  <div class="clear"></div>
</div>

<%= info_block %>