config/routes.rb
Pigeonhole::Application.routes.draw do |map|
  
  # Logout should, of course, work without language
  get 'logout' => 'pigeonhole#logout', :as => 'logout'
  
  constraints(:locale => /[a-z]{2}/) do
    scope "(:locale)" do
      
      get 'logout' => 'pigeonhole#logout', :as => 'logout'
      
      # Self-destructive Binary
      resources :binaries, :only => [:new, :create] do
        member do
          post :new # binaries/new has a password login, we want it to accept POST requests.
        end
      end
      get ':id/:key' => 'binaries#show', :as => 'show_binary', :constraints => { :id => /[a-z0-9]{8}/, :key => /[a-zA-Z0-9]{20}/ }
      
      # Self-destructive Tape
      resources :tapes, :only => [:new, :create] do
        member do
          post :new # tapes/new has a password login, we want it to accept POST requests.
          post :download
        end
      end
      get ':id/:key' => 'tapes#show', :as => 'show_tape', :constraints => { :id => /[a-z0-9]{6}/, :key => /[a-zA-Z0-9]{20}/ }
      
      # Message in a safe
      resources :messages, :only => [:new, :create, :destroy] do
        member do
          post :new # messages/new has a password login, we want it to accept POST requests.
          post :download
          post :attachment
        end
      end
      match ':id' => 'messages#show', :as => 'show_message', :constraints => { :id => /[a-z0-9]{6}/ }
      
      root :to => "pigeonhole#index"
      
    end
  end
end

app/controllers/pigeonhole_controller.rb
class PigeonholeController < ApplicationController
  
  before_filter :login_required, :lock_open_messages
  
  def index
  end
  
  def logout
    reset_session
    redirect_to root_url, :notice => 'You are logged out now. Thank you.'
  end
  
end

app/views/pigeonhole/index.html.erb
<div id="menu_headline">
  <%=t '.headline' %>
</div>

<div class="menu_item orange">
  <%= link_to image_tag('tape.png', :height => 61), new_tape_url %><br/>
  <%=t '.tape' %>
</div>

<div class="menu_item blue">
  <%= link_to image_tag('binary.png', :height => 61), new_binary_url %><br/>
  <%=t '.binary' %>
</div>

<div class="menu_item green">
  <%= link_to image_tag('message.png', :height => 61), new_message_url %><br/>
  <%=t '.message' %>
</div>

<div class="menu_item pink">
  <%= link_to image_tag('trash.png', :height => 61), logout_url %><br/>
  <%=t '.logout' %>
</div>

<div class="clear"></div>

<div id="flags">
  <ul>
  <% I18n.available_locales.each do |locale| %>
    <li><%= link_to image_tag("locales/#{locale}.png"), root_path(:locale => locale) %></li>
  <% end %>
  </ul>
</div>