config/routes.rb
Pigeonhole::Application.routes.draw do |map|
  
  # Logout should, of course, work without language
  get 'logout' => 'pigeonhole#logout', :as => 'logout'
  
  constraints(:locale => /[a-z]{2}/) do
    scope "(:locale)" do
      
      get 'logout' => 'pigeonhole#logout', :as => 'logout'
      
      # Self-destructive Binary
      resources :binaries, :only => [:new, :create] do
        member do
          post :new # binaries/new has a password login, we want it to accept POST requests.
        end
      end
      get ':id/:key' => 'binaries#show', :as => 'show_binary', :constraints => { :id => /[a-z0-9]{8}/, :key => /[a-zA-Z0-9]{20}/ }
      
      # Self-destructive Tape
      resources :tapes, :only => [:new, :create] do
        member do
          post :new # tapes/new has a password login, we want it to accept POST requests.
          post :download
        end
      end
      get ':id/:key' => 'tapes#show', :as => 'show_tape', :constraints => { :id => /[a-z0-9]{6}/, :key => /[a-zA-Z0-9]{20}/ }
      
      # Message in a safe
      resources :messages, :only => [:new, :create, :destroy] do
        member do
          post :new # messages/new has a password login, we want it to accept POST requests.
          post :download
          post :attachment
        end
      end
      match ':id' => 'messages#show', :as => 'show_message', :constraints => { :id => /[a-z0-9]{6}/ }
      
      root :to => "pigeonhole#index"
      
    end
  end
end

app/models/tape.rb
class Tape < Package
  
  validates :body, :presence => true
  
  def load
   super
   begin
     File.delete(path)
     exists? ? nil : self
   rescue Errno::ENOENT => e
     nil
   end
  end

end

app/controllers/tapes_controller.rb
class TapesController < ApplicationController
  
  before_filter :login_required, :except => [ :show ]
  before_filter :lock_open_messages
  
  def show
    @tape = Tape.find(:id => params[:id], :key => params[:key])
    render :template => 'tapes/tampered' and return unless @tape
    perform_login # On successful read, log in the user
  end
  
  def download
    content  = ActiveSupport::Base64.decode64(params[:content].to_s)
    filename = params[:filename].to_s
    send_data content, :filename => filename, :type => 'text/plain' and return
  end
  
  def new
    @tape = Tape.new
  end
  
  def create
    @tape = Tape.new(:body => params[:tape][:body])
    if @tape.save
      @pickup_url = show_tape_url(@tape.id, @tape.key, :locale => nil)
      # Prevent double sending the form
      session[:_csrf_token] = ActiveSupport::SecureRandom.base64(32)
    else
      render :template => 'tapes/new' and return
    end
  end
  
end

app/views/tapes/create.html.erb
<div id="header">
  <%= link_to random_tape_image, root_url  %><br/>
  <%=t '.headline' %>
</div>

<div id="tape" class="pickup">
  <%= @pickup_url %>
</div>

<%= info_block %>

<div id="footer">
  <%= menu_link %>
</div>

app/views/tapes/new.html.erb
<div id="header">
  <%=t '.headline' %>
</div>

<%= form_for @tape do |f| %>

  <div id="tape">
    <%= f.text_area :body %>
  </div>

  <div id="footer">
    <div class="menu_two_items">
      <div class="menu_item">
        <%= image_submit_tag("tape.png", :height => 61) %><br/>
        <%=t '.submit' %>
      </div>
      <div class="menu_item">
        <%= link_to image_tag('trash.png', :height => 61), root_url %><br/>
        <%=t 'cancel' %>
      </div>
    </div>
  </div>
  <div class="clear"></div>

<% end %>

<%= info_block %>

<%= focus_on :tape_body %>

app/views/tapes/show.html.erb
<div id="header">
  <%= link_to random_tape_image, root_url  %><br/>
  <%=t '.headline' %>
</div>

<div id="tape">
  <%=raw sanitize(h(@tape.body).with_line_breaks) %>
  <br/>
  <div class="metadata"><%= @tape.timestamp %></div>
</div>

<div id="footer">
  <div class="menu_two_items">
    <div class="menu_item">
      <% form_tag download_tape_url, :remote => true do |form| %>
        <%= hidden_field_tag :content, ActiveSupport::Base64.encode64(@tape.to_download) %>
        <%= hidden_field_tag :filename, @tape.filename %>
        <%= image_submit_tag("download.png", :height => 61) %><br/>
      <% end %>
      <%=t '.download' %>
    </div>
    <div class="menu_item">
      <%= link_to image_tag('trash.png', :height => 61), root_url %><br/>
      <%=t 'back' %>
    </div>
  </div>
  <div class="clear"></div>
</div>

<%= info_block %>

app/views/tapes/tampered.html.erb
<div id="warning">
  <%= link_to image_tag('tampered.png', :height => 139), root_url %><br/>
  <%=t '.headline' %>
</div>

<div id="footer">
  <%=raw t('.warning') %><br/><br/>
  <%= menu_link %>
</div>

<%= info_block %>