config/routes.rb
Pigeonhole::Application.routes.draw do |map|
  
  # Logout should, of course, work without language
  get 'logout' => 'pigeonhole#logout', :as => 'logout'
  
  constraints(:locale => /[a-z]{2}/) do
    scope "(:locale)" do
      
      get 'logout' => 'pigeonhole#logout', :as => 'logout'
      
      # Self-destructive Binary
      resources :binaries, :only => [:new, :create] do
        member do
          post :new # binaries/new has a password login, we want it to accept POST requests.
        end
      end
      get ':id/:key' => 'binaries#show', :as => 'show_binary', :constraints => { :id => /[a-z0-9]{8}/, :key => /[a-zA-Z0-9]{20}/ }
      
      # Self-destructive Tape
      resources :tapes, :only => [:new, :create] do
        member do
          post :new # tapes/new has a password login, we want it to accept POST requests.
          post :download
        end
      end
      get ':id/:key' => 'tapes#show', :as => 'show_tape', :constraints => { :id => /[a-z0-9]{6}/, :key => /[a-zA-Z0-9]{20}/ }
      
      # Message in a safe
      resources :messages, :only => [:new, :create, :destroy] do
        member do
          post :new # messages/new has a password login, we want it to accept POST requests.
          post :download
          post :attachment
        end
      end
      match ':id' => 'messages#show', :as => 'show_message', :constraints => { :id => /[a-z0-9]{6}/ }
      
      root :to => "pigeonhole#index"
      
    end
  end
end

app/models/binary.rb
class Binary < Tape
  
  attr_accessor :mime, :name
  
  validates :body, :presence => true
  
  def initialize(args={})
    super
    @id   = args.fetch(:id, SecureRandom.hex(4))
    @mime = args.fetch(:mime, 'text/plain')
    @name = args.fetch(:name, filename)
    self
  end
  
  def serialize
    { :body => body,
      :time => time,
      :mime => mime,
      :name => name }.to_yaml
  end
  
  def unserialize(raw)
    yaml = YAML.load(raw)
    @body = yaml.fetch(:body, nil)
    @time = yaml.fetch(:time, nil)
    @mime = yaml.fetch(:mime, nil)
    @name = yaml.fetch(:name, nil)
    self
  end
  
end

app/controllers/binaries_controller.rb
class BinariesController < ApplicationController
  
  before_filter :login_required, :except => [ :show ]
  before_filter :lock_open_messages
  
  def show
    @binary = Binary.find(:id => params[:id], :key => params[:key])
    render :template => 'binaries/tampered' and return unless @binary
    send_data @binary.body, :filename => @binary.name, :type => @binary.mime and return
  end
  
  def new
    @binary = Binary.new
  end
  
  def create
    @binary = if params[:upload].present?
      Binary.new :body => params[:upload].read, :name => params[:upload].original_filename, :mime => params[:upload].content_type
    else
      Binary.new
    end
    if @binary.save
      @pickup_url = show_binary_url(@binary.id, @binary.key, :locale => nil)
      # Prevent double sending the form
      session[:_csrf_token] = ActiveSupport::SecureRandom.base64(32)
    else
      render :template => 'binaries/new' and return
    end
  end
  
end

app/views/binaries/create.html.erb
<div id="header">
  <%= link_to random_binary_image, root_url  %><br/>
  <%=t '.headline' %>
</div>

<div id="tape" class="pickup">
  <%= @pickup_url %>
</div>

<%= info_block %>

<div id="footer">
  <%= menu_link %>
</div>

app/views/binaries/new.html.erb
<div id="header">
  <%=t '.headline' %>
</div>

<%= form_tag binaries_url, { :multipart => true } do |f| %>

  <div id="binary">
    <%= file_field_tag :upload %>
  </div>

  <div id="footer">
    <div class="menu_two_items">
      <div class="menu_item">
        <%= image_submit_tag("binary.png", :height => 61) %><br/>
        <%=t '.submit' %>
      </div>
      <div class="menu_item">
        <%= link_to image_tag('trash.png', :height => 61), root_url %><br/>
        <%=t 'cancel' %>
      </div>
    </div>
  </div>
  <div class="clear"></div>

<% end %>

<%= info_block %>

app/views/binaries/tampered.html.erb
<div id="warning">
  <%= link_to image_tag('tampered.png', :height => 139), root_url %><br/>
  <%=t '.headline' %>
</div>

<div id="footer">
  <%=raw t('.warning') %><br/><br/>
  <%= menu_link %>
</div>

<%= info_block %>